### ISSUE TITLE
Review of Repo

### ISSUE THREAD

**Issue by CityHallin** [pjferguson/azure-resume#1]
Hi, I reviewed your repo and have the following recommendations:

- The backend/api/local.settings.json should never, ever be pushed to your repo. People browsing this public repo can find that info and basically have access to your backend infrastructure. You'll want to create a .gitignore file and make sure local.settings.json is added which prevents it from being saved in your repo. You'll want to immediately remove this from your repo and reset your DB connection string key. 
- Other files/folders can be added to your .gitignore file as they may not be needed in your repo (example: .vscode folder, DS_store, etc.)
- If possible, it would be a good improvement to update your function to use an access key instead of being anonymous. That may be a good extra credit for this project.

**Comment by pjferguson** [comment]
Thank for you the feedback, I realized that the .gitignore file that I had locally was deleted while trying to configure unittesting. Getting everything updated now. That was a huge security vulnerability again, thanks for letting me know.

**Comment by CityHallin** [comment]
No worries 👍. Didn't want you getting a surprise bill one day from tons of people saving or dumping trash in your DB, lol. As long as the keys have been rotated on the actual Azure resource, you're good to go.
